# -*- coding: utf-8 -*-
"""stopwords_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PaGJF__6_q4V6R_zDbwW5cc6SeqzT7Xv
"""

words=["a","an","the","aboard","about","above","across","after","against","along","amid","among","around","as","at","before","behind","below","beneath","beside","besides","between","beyond","both","but","by","concerning","considering","despite","did","down","during","even","except","excepting","excluding","following","for","from","in","inside","into","like","minus","near","of","off","often","on","onto","opposite","others","outside","over","own","past","per","plus","regarding","round","save","since","than","through","to","toward","towards","under","underneath","unlike","until","up","upon","usually","versus","via","whatever","with","within","without","yet"]

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw = set(stopwords.words('english'))

count=0
for d in sw:
  if d not in words:
    words.append(d)
    count=count+1

print(count)
print(len(words))

def swords():
  return words