# -*- coding: utf-8 -*-
"""stopwords_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHweLIr0zAvAzNO0Xy912VGB9dXKztOV
"""

words=["a","an","the","aboard","about","above","across","after","against","along","amid","among","around","as","at","before","behind","below","beneath","beside","besides","between","beyond","both","but","by","concerning","considering","despite","did","down","during","even","except","excepting","excluding","following","for","from","in","inside","into","like","minus","near","of","off","often","on","onto","opposite","others","outside","over","own","past","per","plus","regarding","round","save","since","than","through","to","toward","towards","under","underneath","unlike","until","up","upon","usually","versus","via","whatever","with","within","without","yet"]
def swords():
  return words